#
# Deploy
#
deployment:
  tasks:
    - npm install --no-audit
    - npm run build --prod
    - export DEPLOYPATH=/home/andreasmeis/public_html/snowhub
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;
