#
# Deploy
#
deployment:
  tasks:
    - npm install @angular/cli@15.0.0 -g
    - npm install --force --legacy-peer-deps
    - ng build --prod --base-href https://meis.gr/snowhub/
    - export DEPLOYPATH=/home/andreasmeis/public_html/snowhub
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;
