#
# Deploy
#
deployment:
  tasks:
    - npm install @angular/cli@15.0.0 -g
    - npm ci --force --legacy-peer-deps
    - ng build --base-href https://meis.gr/snowhub/
    - export DEPLOYPATH=/home/example/public_html/snowhub/
    - /dist -R images $DEPLOYPATH
