name: Test

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
          
      - name: Install dependencies
        run: npm install --force
  
      # - name: Run tests
      #   run: npm run test:headless
  
      # - name: Build
      #   run: npm run build:prod
